---
#preparation tasks for 9panel

- set_fact: 
    w9panel_owner: "www-data"
  when: ansible_os_family == 'Debian'

- set_fact: 
    w9panel_owner: "{{ w9panel_webs }}"
  when: ansible_os_family == 'RedHat'

- debug:
    msg: owner is {{w9panel_owner}}

- name: Remove 9panel and example folder if exist
  shell: |
    rm -rf /data/apps/9panel
    rm -rf /data/wwwroot/example
    
# Download,unzip,rename 9panel

- block:
  - name: Create apps Dir
    file:
      path: '/data/apps/9panel'
      state: directory

  - name: Download 9panel from {{ w9panel_download_url }}
    git:
      repo: "{{ w9panel_download_url }}"
      dest: /data/apps/9panel

  - name: Rename directory name
    shell: cd /data/apps; if [ ! -d "9panel" ]; then mv *9panel* 9panel; fi 

# Set 9panel display of infrastructure and apps

- name: set infrastructure of 9Panel to {{w9panel_set_infrastructure}}
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: 'var set_infrastructure='
    line: 'var set_infrastructure="{{ w9panel_set_infrastructure }}";'

- name: set apps of 9Panel {{ w9panel_set_apps | list }}
  lineinfile:
    path: /data/apps/9panel/js/websoft9.js
    regexp: 'var set_apps=\["Example"\];'
    line: 'var set_apps={{ w9panel_set_apps | list }};'


#Copy 9panel to /data/wwwroot/www.example.com if w9panel_set_apps[0]==Example

- block:
  - name: Create /data/wwwroot/example
    file: 
        path: /data/wwwroot/example
        state: directory
        mode: 0750

  - name: Set www.example.com I - copy 9panel
    shell: cp -rp /data/apps/9panel/*  /data/wwwroot/example

  - name: Set www.example.com II - delete unnecessary files
    file:
      path: "/data/wwwroot/example/{{ item }}"
      state: absent
    with_items:
      - db.html
      - ftp.html
      - index.html
      - tools.html

  - name: Set www.example.com II - rename index.html
    command: mv /data/wwwroot/example/example.html /data/wwwroot/example/index.html
  
  

  when: w9panel_set_apps[0] == 'Example'

#System settings for 9panel

- name: Change /data/apps directory Owner
  file: 
      path: /data/apps/9panel
      owner: "{{w9panel_owner}}"
      group: "{{w9panel_owner}}"
      recurse: yes

- name: Change /data/wwwroot directory Owner
  file: 
      path: /data/wwwroot/example
      owner: "{{w9panel_owner}}"
      group: "{{w9panel_owner}}"
      recurse: yes

- block:
  - name: Copy 9panel Configuration
    copy: src=9panel-apache.conf dest=/etc/httpd/conf.d/9panel.conf

  - name: restart Apache
    service: name=apache state=restarted enabled=yes

  when: w9panel_webs == "apache"
  
- block: 
  - name: Copy 9panel Configuration
    copy: src=9panel-nginx.conf dest=/etc/nginx/extra/9panel.conf

  - name: restart Nginx
    service: name=nginx state=restarted enabled=yes

  when: w9panel_webs == "nginx" 

- block:
  - name: Config tomcat
    lineinfile:
      dest: /usr/local/tomcat/conf/server.xml
      insertafter: '/data/wwwroot'
      line: '<Context path="" docBase="/data/wwwroot/example" reloadable="true" />'

  - name: Tomcat example
    shell: mv /usr/local/tomcat/webapps/examples /data/wwwroot/example/demo

  - name: restart Tomcat
    service: name=tomcat state=restarted enabled=yes
  when: w9panel_webs_extra == "tomcat"
